name: Modified JavaCI
jobs:
  ubuntu_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java:
          - 8
          - 11
          - 17
          - 19
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: zulu
          cache: maven
      - name: Build with Maven
        run: mvn clean install -P full "-Dskip.frontend.maven.plugin=true" "-Dfrontend-maven-plugin.node.install=false"
          "-Dfrontend-maven-plugin.yarn.install=false" "-Dmaven.repo.local=/tmp" "-Dfrontend-maven-plugin.skipTests=true"
          "-Dmaven.repo.local.skip=true" "-Dfrontend-maven-plugin.skip=true" "-DskipTests=false"
          "-Dmaven.surefire.reports.skip=true" "-Dfrontend-maven-plugin.yarn.skip=true"
          "-DskipITs" "-Dmaven.javadoc.skip=true" "-Dorg.springframework.skip=true"
          "-Dmaven.invoker.skipReports=true" "-Dvuepress.skip=true" "-Dmaven.test.skip=false"
          "-Dsurefire.useFile=false" "-Dfrontend-maven-plugin.installNodeModules=false"
          "-Dsurefire.reportFormat=plain" "-Dfrontend-maven-plugin.skip.yarn=true"
          "-Dfrontend-maven-plugin.skip.npm=true" "-Dfrontend-maven-plugin.skip.install=true"
          "-Dsurefire.reportsDirectory=target/surefire-reports-empty" "-Dmaven.local.repository.path=target/local-repo"
          "-Dmaven.test.skip=true" "-Dfrontend-maven-plugin.yarn.install.skip=true"
          "-Dfrontend-maven-plugin.yarn.run=false" "-Dfrontend-maven-plugin.yarn.generateDocs=false"
          "-Dfrontend-maven-plugin.yarn.test.skip=true" "-Dmaven.local.repository.path="
          "-Dmaven.local.repository.path=/tmp" "-Dmaven.test.failure.ignore=true"
          "-Dmaven.invoker.localRepositoryPath=/tmp" "-Dmaven.invoker.skip=true" "-Dmaven.invoker.properties=invoker.properties"
          "-Dfrontend-maven-plugin.yarn.install.directory=target/yarn-install" "-Dnative-maven-plugin.link.skip=true"
          "-Dmaven.resources.skip=true" "-Dfrontend-maven-plugin.yarn.useYarnrc=false"
          "-Dfrontend-maven-plugin.yarn.install.directory="
    name: ubuntu_build (${{ matrix.java }})
  windows_build:
    runs-on: windows-2019
    strategy:
      matrix:
        java:
          - 8
          - 11
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: zulu
          cache: maven
      - name: Build with Maven
        run: mvn clean install -P full "-Dskip.frontend.maven.plugin=true" "-Dfrontend-maven-plugin.node.install=false"
          "-Dfrontend-maven-plugin.yarn.install=false" "-Dmaven.repo.local=/tmp" "-Dfrontend-maven-plugin.skipTests=true"
          "-Dmaven.repo.local.skip=true" "-Dfrontend-maven-plugin.skip=true" "-DskipTests=false"
          "-Dmaven.surefire.reports.skip=true" "-Dfrontend-maven-plugin.yarn.skip=true"
          "-DskipITs" "-Dmaven.javadoc.skip=true" "-Dorg.springframework.skip=true"
          "-Dmaven.invoker.skipReports=true" "-Dvuepress.skip=true" "-Dmaven.test.skip=false"
          "-Dsurefire.useFile=false" "-Dfrontend-maven-plugin.installNodeModules=false"
          "-Dsurefire.reportFormat=plain" "-Dfrontend-maven-plugin.skip.yarn=true"
          "-Dfrontend-maven-plugin.skip.npm=true" "-Dfrontend-maven-plugin.skip.install=true"
          "-Dsurefire.reportsDirectory=target/surefire-reports-empty" "-Dmaven.local.repository.path=target/local-repo"
          "-Dmaven.test.skip=true" "-Dfrontend-maven-plugin.yarn.install.skip=true"
          "-Dfrontend-maven-plugin.yarn.run=false" "-Dfrontend-maven-plugin.yarn.generateDocs=false"
          "-Dfrontend-maven-plugin.yarn.test.skip=true" "-Dmaven.local.repository.path="
          "-Dmaven.local.repository.path=/tmp" "-Dmaven.test.failure.ignore=true"
          "-Dmaven.invoker.localRepositoryPath=/tmp" "-Dmaven.invoker.skip=true" "-Dmaven.invoker.properties=invoker.properties"
          "-Dfrontend-maven-plugin.yarn.install.directory=target/yarn-install" "-Dnative-maven-plugin.link.skip=true"
          "-Dmaven.resources.skip=true" "-Dfrontend-maven-plugin.yarn.useYarnrc=false"
          "-Dfrontend-maven-plugin.yarn.install.directory="
    name: windows_build (${{ matrix.java }})
  macos_build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java:
          - 8
          - 11
        os:
          - macos-latest
          - macos-14
    steps:
      - uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: zulu
          cache: maven
      - name: Build with Maven
        run: mvn clean install -P full "-Dskip.frontend.maven.plugin=true" "-Dfrontend-maven-plugin.node.install=false"
          "-Dfrontend-maven-plugin.yarn.install=false" "-Dmaven.repo.local=/tmp" "-Dfrontend-maven-plugin.skipTests=true"
          "-Dmaven.repo.local.skip=true" "-Dfrontend-maven-plugin.skip=true" "-DskipTests=false"
          "-Dmaven.surefire.reports.skip=true" "-Dfrontend-maven-plugin.yarn.skip=true"
          "-DskipITs" "-Dmaven.javadoc.skip=true" "-Dorg.springframework.skip=true"
          "-Dmaven.invoker.skipReports=true" "-Dvuepress.skip=true" "-Dmaven.test.skip=false"
          "-Dsurefire.useFile=false" "-Dfrontend-maven-plugin.installNodeModules=false"
          "-Dsurefire.reportFormat=plain" "-Dfrontend-maven-plugin.skip.yarn=true"
          "-Dfrontend-maven-plugin.skip.npm=true" "-Dfrontend-maven-plugin.skip.install=true"
          "-Dsurefire.reportsDirectory=target/surefire-reports-empty" "-Dmaven.local.repository.path=target/local-repo"
          "-Dmaven.test.skip=true" "-Dfrontend-maven-plugin.yarn.install.skip=true"
          "-Dfrontend-maven-plugin.yarn.run=false" "-Dfrontend-maven-plugin.yarn.generateDocs=false"
          "-Dfrontend-maven-plugin.yarn.test.skip=true" "-Dmaven.local.repository.path="
          "-Dmaven.local.repository.path=/tmp" "-Dmaven.test.failure.ignore=true"
          "-Dmaven.invoker.localRepositoryPath=/tmp" "-Dmaven.invoker.skip=true" "-Dmaven.invoker.properties=invoker.properties"
          "-Dfrontend-maven-plugin.yarn.install.directory=target/yarn-install" "-Dnative-maven-plugin.link.skip=true"
          "-Dmaven.resources.skip=true" "-Dfrontend-maven-plugin.yarn.useYarnrc=false"
          "-Dfrontend-maven-plugin.yarn.install.directory="
    name: macos_build (${{ matrix.java }}, ${{ matrix.os }})
'on':
  - push
  - workflow_dispatch
